// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/currencyservice.proto

package microshopping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_currencyservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currencyservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_currencyservice_proto_rawDescGZIP(), []int{0}
}

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCode  string                 `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"` // 货币代码，例如 "USD", "EUR"
	Units         int64                  `protobuf:"varint,2,opt,name=units,proto3" json:"units,omitempty"`                                  // 整数部分
	Nanos         int32                  `protobuf:"varint,3,opt,name=nanos,proto3" json:"nanos,omitempty"`                                  // 小数部分，范围 -999,999,999 到 +999,999,999
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_proto_currencyservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currencyservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_proto_currencyservice_proto_rawDescGZIP(), []int{1}
}

func (x *Money) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Money) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Money) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

type GetSupportedCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyCodes []string               `protobuf:"bytes,1,rep,name=currency_codes,json=currencyCodes,proto3" json:"currency_codes,omitempty"` // 支持的货币代码列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedCurrenciesResponse) Reset() {
	*x = GetSupportedCurrenciesResponse{}
	mi := &file_proto_currencyservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedCurrenciesResponse) ProtoMessage() {}

func (x *GetSupportedCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currencyservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*GetSupportedCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_currencyservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetSupportedCurrenciesResponse) GetCurrencyCodes() []string {
	if x != nil {
		return x.CurrencyCodes
	}
	return nil
}

type CurrencyConversionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *Money                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`                   // 源货币金额
	ToCode        string                 `protobuf:"bytes,2,opt,name=to_code,json=toCode,proto3" json:"to_code,omitempty"` // 目标货币代码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyConversionRequest) Reset() {
	*x = CurrencyConversionRequest{}
	mi := &file_proto_currencyservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyConversionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyConversionRequest) ProtoMessage() {}

func (x *CurrencyConversionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currencyservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyConversionRequest.ProtoReflect.Descriptor instead.
func (*CurrencyConversionRequest) Descriptor() ([]byte, []int) {
	return file_proto_currencyservice_proto_rawDescGZIP(), []int{3}
}

func (x *CurrencyConversionRequest) GetFrom() *Money {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *CurrencyConversionRequest) GetToCode() string {
	if x != nil {
		return x.ToCode
	}
	return ""
}

var File_proto_currencyservice_proto protoreflect.FileDescriptor

const file_proto_currencyservice_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/currencyservice.proto\x12\rmicroshopping\"\a\n" +
	"\x05Empty\"X\n" +
	"\x05Money\x12#\n" +
	"\rcurrency_code\x18\x01 \x01(\tR\fcurrencyCode\x12\x14\n" +
	"\x05units\x18\x02 \x01(\x03R\x05units\x12\x14\n" +
	"\x05nanos\x18\x03 \x01(\x05R\x05nanos\"G\n" +
	"\x1eGetSupportedCurrenciesResponse\x12%\n" +
	"\x0ecurrency_codes\x18\x01 \x03(\tR\rcurrencyCodes\"^\n" +
	"\x19CurrencyConversionRequest\x12(\n" +
	"\x04from\x18\x01 \x01(\v2\x14.microshopping.MoneyR\x04from\x12\x17\n" +
	"\ato_code\x18\x02 \x01(\tR\x06toCode2\xbf\x01\n" +
	"\x0fCurrencyService\x12_\n" +
	"\x16GetSupportedCurrencies\x12\x14.microshopping.Empty\x1a-.microshopping.GetSupportedCurrenciesResponse\"\x00\x12K\n" +
	"\aConvert\x12(.microshopping.CurrencyConversionRequest\x1a\x14.microshopping.Money\"\x00B\x17Z\x15./proto;microshoppingb\x06proto3"

var (
	file_proto_currencyservice_proto_rawDescOnce sync.Once
	file_proto_currencyservice_proto_rawDescData []byte
)

func file_proto_currencyservice_proto_rawDescGZIP() []byte {
	file_proto_currencyservice_proto_rawDescOnce.Do(func() {
		file_proto_currencyservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_currencyservice_proto_rawDesc), len(file_proto_currencyservice_proto_rawDesc)))
	})
	return file_proto_currencyservice_proto_rawDescData
}

var file_proto_currencyservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_currencyservice_proto_goTypes = []any{
	(*Empty)(nil),                          // 0: microshopping.Empty
	(*Money)(nil),                          // 1: microshopping.Money
	(*GetSupportedCurrenciesResponse)(nil), // 2: microshopping.GetSupportedCurrenciesResponse
	(*CurrencyConversionRequest)(nil),      // 3: microshopping.CurrencyConversionRequest
}
var file_proto_currencyservice_proto_depIdxs = []int32{
	1, // 0: microshopping.CurrencyConversionRequest.from:type_name -> microshopping.Money
	0, // 1: microshopping.CurrencyService.GetSupportedCurrencies:input_type -> microshopping.Empty
	3, // 2: microshopping.CurrencyService.Convert:input_type -> microshopping.CurrencyConversionRequest
	2, // 3: microshopping.CurrencyService.GetSupportedCurrencies:output_type -> microshopping.GetSupportedCurrenciesResponse
	1, // 4: microshopping.CurrencyService.Convert:output_type -> microshopping.Money
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_currencyservice_proto_init() }
func file_proto_currencyservice_proto_init() {
	if File_proto_currencyservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_currencyservice_proto_rawDesc), len(file_proto_currencyservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_currencyservice_proto_goTypes,
		DependencyIndexes: file_proto_currencyservice_proto_depIdxs,
		MessageInfos:      file_proto_currencyservice_proto_msgTypes,
	}.Build()
	File_proto_currencyservice_proto = out.File
	file_proto_currencyservice_proto_goTypes = nil
	file_proto_currencyservice_proto_depIdxs = nil
}
